/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.dxWeather;

import java.io.IOException;
import javax.swing.JFrame;

/**
 *
 * @author debayan
 */
public class wWidget extends javax.swing.JFrame 
{
    String temperature;
    String weatherDescription;
    String location;
    String humidity;
    String maxTemp;
    String minTemp;

    public void setLocationName(String locationNamePassed)
    {
        location = locationNamePassed;
    }
    
    public void setTemperature(String tempPassed)
    {
        temperature = tempPassed;
    }
    
    public void setWeatherDescription(String weatherDescriptionPassed)
    {
        weatherDescription = weatherDescriptionPassed;
    }
    
    public void setHumidity(String humidityPassed)
    {
        humidity = humidityPassed;
    }
    
    public void setMaxTemp(String maxTempPassed)
    {
        maxTemp = maxTempPassed;
    }
    
    public void setMinTemp(String minTempPassed)
    {
        minTemp = minTempPassed;
    }
    
    public void setUnit(String unitPassed)
    {
        tempUnitLabel.setText(unitPassed);
    }
    
    public void refresh()
    {
        tempLabel.setText(temperature);
        locationLabel.setText(location);
        descriptionLabel.setText(weatherDescription);  
        jLabel6.setText(humidity);
        jLabel5.setText(maxTemp);
        jLabel7.setText(minTemp);
        toBack();
    }
    
    
    /**
     * Creates new form wWidget
     */
    public wWidget() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        tempLabel = new javax.swing.JLabel();
        tempUnitLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DX Weather Widget");
        setFocusable(false);
        setLocation(new java.awt.Point(1070, 0));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel4.setLayout(null);

        tempLabel.setFont(new java.awt.Font("Courier 10 Pitch", 0, 48)); // NOI18N
        tempLabel.setText("69");
        jPanel4.add(tempLabel);
        tempLabel.setBounds(10, 0, 120, 60);

        tempUnitLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        tempUnitLabel.setText("°C");
        jPanel4.add(tempUnitLabel);
        tempUnitLabel.setBounds(70, 0, 80, 40);

        locationLabel.setFont(new java.awt.Font("FreeSans", 0, 21)); // NOI18N
        locationLabel.setText("New Delhi, IN");
        jPanel4.add(locationLabel);
        locationLabel.setBounds(10, 50, 140, 30);

        descriptionLabel.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        descriptionLabel.setText("Clear Sky");
        jPanel4.add(descriptionLabel);
        descriptionLabel.setBounds(10, 80, 130, 23);

        jLabel2.setText("Humidity :");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(160, 30, 70, 18);

        jLabel6.setText("jLabel5");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(240, 30, 49, 18);

        jLabel4.setText("Max Temp : ");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(160, 50, 80, 18);

        jLabel5.setText("jLabel5");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(240, 50, 49, 18);

        jLabel3.setText("Min Temp :");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(160, 70, 74, 18);

        jLabel7.setText("jLabel5");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(240, 70, 49, 18);

        exitButton.setText("x");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel4.add(exitButton);
        exitButton.setBounds(270, 140, 30, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/dxWeather/index.jpeg"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(0, 0, 300, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        console.pln("Sucessfully closed!");
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wWidget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wWidget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wWidget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wWidget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wWidget().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel tempUnitLabel;
    // End of variables declaration//GEN-END:variables
}
